security:
    enable_authenticator_manager: true
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users
            http_basic:
                realm: Secured Area

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # allow unauthenticated users to access the login form
        - { path: ^/, roles: PUBLIC_ACCESS }
