services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Tests\:
        resource: '../tests/'
        exclude:
            - '../tests/bootstrap.php'
